[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command   = ""
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
    package = "@netlify/plugin-nextjs"
