import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';

import Providers from './providers';
import NavBar from './components/navbar';
import Footer from './components/footer';
import Loading from './loading';

import '../assets/scss/custom.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <div data-testid="container" className="container mt-100">
            <Suspense fallback={<Loading />}>
              <main data-testid="main">{children}</main>
            </Suspense>
            <Footer data-testid="footer" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
